defmodule Mix.Tasks.Zc.Gen.Contracts do
  @shortdoc "Generate (or --check) assets/js/contracts.js from Web.Contracts"

  @moduledoc """
  The cross-language half of V32's contract single-sourcing: the JS side of a
  server↔JS contract (`push_event(:item_removed)` ↔ `handleEvent(...)`, hook
  names, stream dom-ids) must agree with `ZeroCoupled.Web.Contracts`. Mirror
  the `zc.gen` discipline:

      mix zc.gen.contracts             # write assets/js/contracts.js
      mix zc.gen.contracts --check     # fail if the committed JS drifted

  `--check` is wired into the `test` alias. The task also reports any contract
  key whose value is referenced by nobody in `lib/` + `assets/js/` — a dead
  contract (warning only, not a failure: the scan is a text heuristic).
  """

  use Mix.Task

  @requirements ["compile"]

  @path "assets/js/contracts.js"

  @impl true
  def run(args) do
    {opts, _, _} = OptionParser.parse(args, switches: [check: :boolean])

    js = generate(ZeroCoupled.Web.Contracts.__contracts__())

    if opts[:check] do
      cond do
        not File.exists?(@path) ->
          Mix.raise("#{@path} is missing — run `mix zc.gen.contracts`")

        File.read!(@path) == js ->
          Mix.shell().info("ok  #{@path}")

        true ->
          Mix.raise("#{@path} is stale — run `mix zc.gen.contracts` and commit the result")
      end
    else
      File.write!(@path, js)
      Mix.shell().info("wrote #{@path}")
    end

    report_dead_contracts()
  end

  defp generate(contracts) do
    blocks =
      for {name, key} <- [
            {"Events", :events},
            {"Streams", :streams},
            {"Hooks", :hooks},
            {"PushEvents", :push_events}
          ] do
        entries =
          contracts[key]
          |> Enum.sort()
          |> Enum.map_join(",\n", fn {k, v} -> ~s(  "#{k}": "#{v}") end)

        "export const #{name} = {\n#{entries}\n};"
      end

    """
    // GENERATED by `mix zc.gen.contracts` — do not edit.
    // Source of truth: ZeroCoupled.Web.Contracts. `--check` fails the build on drift.
    """ <> Enum.join(blocks, "\n\n") <> "\n"
  end

  # A contract value referenced nowhere is dead weight in the table. Text
  # scan over lib/ + assets/js (excluding the generated file itself).
  defp report_dead_contracts do
    contracts = ZeroCoupled.Web.Contracts.__contracts__()

    sources =
      (Path.wildcard("lib/**/*.ex") ++ (Path.wildcard("assets/js/*.js") -- [@path]))
      |> Enum.map_join("\n", &File.read!/1)

    dead =
      for {group, map} <- contracts,
          {key, value} <- map,
          not String.contains?(sources, to_string(value)),
          do: "#{group}:#{key} (\"#{value}\")"

    unless dead == [] do
      Mix.shell().info("warning: dead contract(s) referenced by nobody: #{Enum.join(dead, ", ")}")
    end
  end
end
